export const CSS_PROPERTIES = [
  // Layout Properties
  {
    key: "display",
    values: [
      "block",
      "inline",
      "inline-block",
      "flex",
      "inline-flex",
      "grid",
      "inline-grid",
      "table",
      "table-row",
      "table-cell",
      "none",
    ],
  },
  {
    key: "position",
    values: ["static", "relative", "absolute", "fixed", "sticky"],
  },
  { key: "float", values: ["none", "left", "right"] },
  { key: "clear", values: ["none", "left", "right", "both"] },
  {
    key: "overflow",
    values: ["visible", "hidden", "scroll", "auto", "overlay"],
  },
  { key: "z-index", values: ["auto"] },

  // Box Model
  {
    key: "width",
    values: ["auto", "fit-content", "max-content", "min-content"],
  },
  {
    key: "height",
    values: ["auto", "fit-content", "max-content", "min-content"],
  },
  {
    key: "min-width",
    values: ["auto", "fit-content", "max-content", "min-content"],
  },
  {
    key: "max-width",
    values: ["none", "fit-content", "max-content", "min-content"],
  },
  {
    key: "min-height",
    values: ["auto", "fit-content", "max-content", "min-content"],
  },
  {
    key: "max-height",
    values: ["none", "fit-content", "max-content", "min-content"],
  },

  // Spacing
  { key: "margin", values: ["auto"] },
  { key: "margin-top", values: ["auto"] },
  { key: "margin-right", values: ["auto"] },
  { key: "margin-bottom", values: ["auto"] },
  { key: "margin-left", values: ["auto"] },
  { key: "padding", values: [] },
  { key: "padding-top", values: [] },
  { key: "padding-right", values: [] },
  { key: "padding-bottom", values: [] },
  { key: "padding-left", values: [] },

  // Colors & Backgrounds
  {
    key: "color",
    values: ["inherit", "initial", "unset", "transparent", "currentcolor"],
  },
  {
    key: "background-color",
    values: ["inherit", "initial", "unset", "transparent", "currentcolor"],
  },
  { key: "background-image", values: ["none", "inherit", "initial", "unset"] },
  {
    key: "background-size",
    values: ["auto", "cover", "contain", "inherit", "initial", "unset"],
  },
  {
    key: "background-position",
    values: [
      "left top",
      "left center",
      "left bottom",
      "right top",
      "right center",
      "right bottom",
      "center top",
      "center center",
      "center bottom",
      "inherit",
      "initial",
      "unset",
    ],
  },
  {
    key: "background-repeat",
    values: [
      "repeat",
      "repeat-x",
      "repeat-y",
      "no-repeat",
      "space",
      "round",
      "inherit",
      "initial",
      "unset",
    ],
  },
  { key: "opacity", values: ["inherit", "initial", "unset"] },

  // Borders
  { key: "border", values: ["inherit", "initial", "unset"] },
  {
    key: "border-width",
    values: ["0", "1px", "2px", "thin", "medium", "thick"],
  },
  {
    key: "border-style",
    values: [
      "none",
      "solid",
      "dashed",
      "dotted",
      "double",
      "groove",
      "ridge",
      "inset",
      "outset",
    ],
  },
  {
    key: "border-color",
    values: ["black", "white", "red", "blue", "#000", "transparent"],
  },
  {
    key: "border-radius",
    values: ["0", "5px", "10px", "50%", "10px 20px", "10px 20px 30px 40px"],
  },
  { key: "border-top", values: ["none", "1px solid black", "2px dashed red"] },
  {
    key: "border-right",
    values: ["none", "1px solid black", "2px dashed red"],
  },
  {
    key: "border-bottom",
    values: ["none", "1px solid black", "2px dashed red"],
  },
  { key: "border-left", values: ["none", "1px solid black", "2px dashed red"] },

  // Typography
  {
    key: "font-family",
    values: [
      "inherit",
      "initial",
      "unset",
      "serif",
      "sans-serif",
      "monospace",
      "cursive",
      "fantasy",
      "system-ui",
    ],
  },
  {
    key: "font-size",
    values: [
      "inherit",
      "initial",
      "unset",
      "xx-small",
      "x-small",
      "small",
      "medium",
      "large",
      "x-large",
      "xx-large",
      "larger",
      "smaller",
    ],
  },
  {
    key: "font-weight",
    values: [
      "inherit",
      "initial",
      "unset",
      "normal",
      "bold",
      "bolder",
      "lighter",
    ],
  },
  {
    key: "font-style",
    values: ["inherit", "initial", "unset", "normal", "italic", "oblique"],
  },
  {
    key: "text-align",
    values: [
      "inherit",
      "initial",
      "unset",
      "left",
      "right",
      "center",
      "justify",
      "start",
      "end",
    ],
  },
  {
    key: "text-decoration",
    values: [
      "inherit",
      "initial",
      "unset",
      "none",
      "underline",
      "overline",
      "line-through",
      "blink",
    ],
  },
  {
    key: "text-transform",
    values: [
      "inherit",
      "initial",
      "unset",
      "none",
      "capitalize",
      "uppercase",
      "lowercase",
    ],
  },
  { key: "line-height", values: ["inherit", "initial", "unset", "normal"] },
  { key: "letter-spacing", values: ["inherit", "initial", "unset", "normal"] },
  { key: "word-spacing", values: ["inherit", "initial", "unset", "normal"] },

  // Flexbox
  {
    key: "flex-direction",
    values: [
      "inherit",
      "initial",
      "unset",
      "row",
      "row-reverse",
      "column",
      "column-reverse",
    ],
  },
  {
    key: "flex-wrap",
    values: ["inherit", "initial", "unset", "nowrap", "wrap", "wrap-reverse"],
  },
  {
    key: "justify-content",
    values: [
      "inherit",
      "initial",
      "unset",
      "flex-start",
      "flex-end",
      "center",
      "space-between",
      "space-around",
      "space-evenly",
    ],
  },
  {
    key: "align-items",
    values: [
      "inherit",
      "initial",
      "unset",
      "normal",
      "stretch",
      "flex-start",
      "flex-end",
      "center",
      "baseline",
    ],
  },
  {
    key: "align-content",
    values: [
      "inherit",
      "initial",
      "unset",
      "normal",
      "stretch",
      "flex-start",
      "flex-end",
      "center",
      "space-between",
      "space-around",
    ],
  },
  { key: "flex", values: ["inherit", "initial", "unset", "none", "auto"] },
  { key: "flex-grow", values: ["inherit", "initial", "unset"] },
  { key: "flex-shrink", values: ["inherit", "initial", "unset"] },
  {
    key: "flex-basis",
    values: ["inherit", "initial", "unset", "auto", "content"],
  },
  {
    key: "align-self",
    values: [
      "inherit",
      "initial",
      "unset",
      "auto",
      "normal",
      "stretch",
      "flex-start",
      "flex-end",
      "center",
      "baseline",
    ],
  },

  // Grid
  {
    key: "grid-template-columns",
    values: [
      "inherit",
      "initial",
      "unset",
      "none",
      "auto",
      "max-content",
      "min-content",
    ],
  },
  {
    key: "grid-template-rows",
    values: [
      "inherit",
      "initial",
      "unset",
      "none",
      "auto",
      "max-content",
      "min-content",
    ],
  },
  { key: "grid-gap", values: ["inherit", "initial", "unset", "normal"] },
  { key: "grid-column", values: ["inherit", "initial", "unset", "auto"] },
  { key: "grid-row", values: ["inherit", "initial", "unset", "auto"] },

  // Transitions & Animations
  { key: "transition", values: ["inherit", "initial", "unset", "none", "all"] },
  { key: "transform", values: ["inherit", "initial", "unset", "none"] },
  { key: "animation", values: ["inherit", "initial", "unset", "none"] },

  // Cursor & Interaction
  {
    key: "cursor",
    values: [
      "inherit",
      "initial",
      "unset",
      "auto",
      "default",
      "none",
      "context-menu",
      "help",
      "pointer",
      "progress",
      "wait",
      "cell",
      "crosshair",
      "text",
      "vertical-text",
      "alias",
      "copy",
      "move",
      "no-drop",
      "not-allowed",
      "grab",
      "grabbing",
      "e-resize",
      "n-resize",
      "ne-resize",
      "nw-resize",
      "s-resize",
      "se-resize",
      "sw-resize",
      "w-resize",
      "ew-resize",
      "ns-resize",
      "nesw-resize",
      "nwse-resize",
      "col-resize",
      "row-resize",
      "all-scroll",
      "zoom-in",
      "zoom-out",
    ],
  },
  {
    key: "user-select",
    values: [
      "inherit",
      "initial",
      "unset",
      "auto",
      "text",
      "none",
      "contain",
      "all",
    ],
  },
  {
    key: "pointer-events",
    values: [
      "inherit",
      "initial",
      "unset",
      "auto",
      "none",
      "visiblePainted",
      "visibleFill",
      "visibleStroke",
      "visible",
      "painted",
      "fill",
      "stroke",
      "all",
    ],
  },

  // Visibility
  {
    key: "visibility",
    values: ["inherit", "initial", "unset", "visible", "hidden", "collapse"],
  },

  // Box Shadow
  {
    key: "box-shadow",
    values: ["inherit", "initial", "unset", "none", "inset"],
  },

  // Text Shadow
  { key: "text-shadow", values: ["inherit", "initial", "unset", "none"] },
];
